# Generated by Django 2.1.4 on 2018-12-04 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('pwID', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=260)),
                ('work_package', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkEffort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('work_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('work_issue', models.TextField(null=True)),
                ('project_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.ProjectWork')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
