# Generated by Django 2.1.4 on 2018-12-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectwork',
            name='work_package',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
    ]
